config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resources :locations, only: [ :show, :edit, :update, :destroy ]
  # resources :contents, only: [ :show, :edit, :update, :destroy ]
  # resources :images, only: [ :show, :edit, :update, :destroy ]

  # get '/' => 'locations#directory', :constraints => { :subdomain => 'locations' }, as: 'location_directory_subdomain'
  # get '/:id' => 'locations#show', :constraints => { :subdomain => "locations" }, as: 'location_subdomain'
  get '/:id' => 'locations#show', :constraints => { :subdomain => /^(?:(?!www).)*$/ }, as: 'location_subdomain'

  resources :brands, as: 'brands' do 

    resources :locations, as: 'locations', except: :show do
      collection do
        get '/import_export' => 'locations#import_export', as: "import_export"
        post :import
      end
    end

    resources :locations, as: 'locations', only: [:show], shallow: true

    resources :contents, as: 'contents'

    resources :images, as: 'images'

  end

  namespace :api do
    namespace :v1 do
      get '/brands' => 'brands#index'
      get '/brands/all' => 'brands#all'
      get '/locations' => 'locations#index'
      get '/images' => 'images#index'
      get '/contents' => 'contents#index'
    end
  end

  # get '/brands/:brand_id/locations' => 'locations#index', as: 'brand_location'
  # get '/brands/:brand_id/directory' => 'locations#directory', as: 'location_directory'
  # get '/brands/:brand_id/content' => 'contents#index', as: 'brand_content'
  # get '/brands/:brand_id/images' => 'images#index', as: 'brand_image'
  # get '/brands' => 'brands#index', as: 'brand'

  # get '/brands/:brand_id/locations/new' => 'locations#new', as: 'brand_location_new'
  # get '/brands/:brand_id/content/new' => 'contents#new', as: 'brand_content_new'
  # get '/brands/:brand_id/images/new' => 'images#new', as: 'brand_image_new'
  # get '/brands/new' => 'brands#new', as: 'brand_new'

  # post '/brands/:brand_id/locations' => 'locations#create'
  # post '/brands/:brand_id/content' => 'contents#create'
  # post '/brands/:brand_id/images' => 'images#create'
  # post '/brands' => 'brands#create', as: 'brand_create'

  # get '/brands/:brand_id/locations/:id' => 'locations#show', as: 'brand_location_show'
  # get '/brands/:brand_id/content/:id' => 'contents#show', as: 'brand_content_show'
  # get '/brands/:brand_id/images/:id' => 'images#show', as: 'brand_image_show'
  # get '/brands/:id' => 'brands#show', as: "brand_show"

  # get '/brands/:brand_id/locations/:id/edit' => 'locations#edit', as: 'brand_location_edit'
  # get '/brands/:brand_id/content/:id/edit' => 'contents#edit', as: 'brand_content_edit'
  # get '/brands/:brand_id/images/:id/edit' => 'images#edit', as: 'brand_image_edit'
  # get '/brands/:id/edit' => 'brands#edit', as: 'brand_edit'

  # patch '/brands/:brand_id/locations/:id' => 'locations#update', as: 'brand_location_update'
  # patch '/brands/:brand_id/content/:id' => 'contents#update', as: 'brand_content_update'
  # patch '/brands/:brand_id/images/:id' => 'images#update', as: 'brand_image_update'
  # patch '/brands/:id' => 'brands#update', as: 'brand_update'

  # delete '/brands/:brand_id/locations/:id' => 'locations#destroy', as: 'brand_location_delete'
  # delete '/brands/:brand_id/content/:id' => 'contents#destroy', as: 'brand_content_delete'
  # delete '/brands/:brand_id/images/:id' => 'images#destroy', as: 'brand_image_delete'
  # delete '/brands/:id' => 'brands#destroy', as: 'brand_delete'

  # Contact Email Page
  post '/contact' => 'pages#contact_email', as: 'contact_email'

  post '/:id' => 'locations#send_mail', as: 'location_send_email'

  #static pages
  root "pages#show", page: "home", as: 'home'
  get "/*page" => "pages#show"
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :contentable, polymorphic: true

  validates :content_name, :content_field, presence: true

  def self.search(search)
    if Rails.env.production?
      where("content_name ILIKE ? OR cast(id as text) ILIKE ?", "%#{search}%", "%#{search}%")
    else
      where("content_name LIKE ? OR id LIKE ?", "%#{search}%", "%#{search}%") 
    end
  end

  def content_updated_at
    self.updated_at.strftime("%e %b %Y %I:%M%p")
  end

  def content_created_at
    self.created_at.strftime("%e %b %Y %I:%M%p")
  end
end

app/controllers/api/v1/contents_controller.rb
class Api::V1::ContentsController < ApplicationController

  def index
    @contents = current_user.brands.find(params[:brand_id]).contents
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_filter :load_brand
  layout "cms_locations_layout"

  def index
    @searchPlaceholder = "Search Content"

    if current_user.brands.exists?(params[:brand_id])
      @contents = @brand.contents.all

      if params[:search]
        @contents = @brand.contents.search(params[:search])
      else
        @contents = @brand.contents.all
      end

      if params[:filter] && params[:filter_order]
        @contents = @contents.order(params[:filter] => params[:filter_order])
      end
    else
      redirect_to "/"
    end

    # if params[:filter] && params[:filter_order]
    #   @locations = Location.order(params[:filter] => params[:filter_order])
    # end
  end

  def new
    @content = Content.new
  end

  def create
    @content = @brand.contents.create({ 
      content_name: params[:content_name],
      content_category: params[:content_category],
      content_field: params[:content_field]
      })

    if @content.save
    
      flash[:success] = "New Content Created"

      redirect_to brand_contents_path

    else
      render :new
    end
  end

  def show
    @content = @brand.contents.find(params[:id])
  end

  def edit
    @content = @brand.contents.find(params[:id])
  end

  def update
    @content = @brand.contents.find(params[:id])

    @content.update({ 
      content_name: params[:content_name],
      content_category: params[:content_category],
      content_field: params[:content_field]
      })

    if @content.save

      flash[:info] = "Content Updated"

      redirect_to brand_contents_path

    else
      render :edit
    end
  end

  def destroy
    @content = @brand.contents.find(params[:id])
    @content.destroy

    flash[:danger] = "Content Deleted"

    redirect_to brand_contents_path
  end

  private

  def load_brand
    @brand = Brand.find(params[:brand_id])
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/edit.html.erb
<section class="section">  
  <div class="container">

    <% if @content.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>
     
        <ul>
        <% @content.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-12">
      <h1>Edit Content  <span class="edit-name">: <%= @content.content_name %></span></h1>

      <!-- <ul class="nav nav-tabs">
        <li role="presentation"><a href="#local">Local</a></li>
        <li role="presentation"><a href="#about">About</a></li>
        <li role="presentation"><a href="#meta">Meta</a></li>
      </ul> -->

      <%= form_tag brand_content_path, method: :patch do %>
      
      <div class="row">
        <div class="col-md-12">
          <table class="table table-hover">
            <tbody>  
              <tr>
                <td><%= label_tag :title %></td>
                <td><%= text_field_tag :content_name, @content.content_name, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :category %></td>
                <td><%= text_field_tag :content_category, @content.content_category, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :content %></td>
                <td><%= text_area_tag :content_field, @content.content_field, class: "form-control", size: "20x10" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <%= submit_tag 'Update Location', class: "btn btn-cta-cms-search btn-xs"%>

      <% end %>
    </div>  
  </div>
</section>

app/views/contents/index.html.erb
<script>
  window.brandId = <%= @contents.first.contentable_id unless @contents.first.blank? %>
</script>

<section class="section">  
  <div class="container">

    <table class="table table-hover table-responsive">
      <thead>
        <tr>
          <th class="hidden-xs">ID</th>
          <th>Name</th>
          <th class="hidden-xs hidden-sm">Category</th>
          <th class="hidden-xs">Updated</th>
          <th class="hidden-xs">Created</th>
          <th>View</th> 
          <th>Edit</th>
          <th>Delete</th>  
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="content in contents | filter: searchFilter | orderBy:sortByAttribute:descending">
          <td class="hidden-xs">{{ content.id }}</td>
          <td>{{ content.content_name }}</td>
          <td class="hidden-xs hidden-sm">{{ content.content_category }}</td>
          <td class="hidden-xs">{{ content.updated_at }}</td>
          <td class="hidden-xs">{{ content.created_at }}</td>
          <td>
            <%= link_to 'View', "#contentModal-{{content.id}}", "data-toggle" => "modal", class: 'btn btn-cta-cms-view btn-xs' %>
          </td>
          <td>
            <% url_escaped_href = edit_brand_content_path('{{ content.brand_id }}', '{{ content.id }}') 
              edit_brand_content_path = URI::unescape(url_escaped_href)
            %>
            <a ng-href="<%= edit_brand_content_path %>" class="btn btn-cta-cms-view btn-xs">Edit</a>
          </td> 
          <td>
            <%= link_to "Delete", "/brands/{{ content.brand_id }}/contents/{{ content.id }}", method: :delete, class: "btn btn-cta-cms-delete btn-xs", data: {confirm: "Are you sure?"}  %>
          </td>  
        </tr>
      </tbody>
    </table>

  </div>
</section>

<% @contents.each do |content| %>
<!--- MODAL -->
<div class="modal fade" id="contentModal-<%= content.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <h2><%= content.content_name %></h2>
        <p><%= content.content_field %>></p>
      </div>
    </div>
  </div>
</div>
<!--END MODAL-->
<% end %>

app/views/contents/new.html.erb
<section class="section">  
  <div class="container">

    <% if @content.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>
     
        <ul>
        <% @content.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-12">
      <h1>Add Content</h1>

      <%= form_tag brand_contents_path, method: :post do %>

        <table class="table table-hover">
          <tbody>  
              <tr>
                <td><%= label_tag :title %></td>
                <td><%= text_field_tag :content_name, @content.content_name, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :category %></td>
                <td><%= text_field_tag :content_category, @content.content_category, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :content %></td>
                <td><%= text_area_tag :content_field, @content.content_field, class: "form-control", size: "20x10" %></td>
              </tr>
          </tbody>
        </table>

      <%= submit_tag 'Add Content', class: "btn btn-cta-cms-search btn-xs"%>

      <% end %>
    </div>  
  </div>
</section>

app/views/contents/show.html.erb
<section class="section">  
  <div class="container">
    <p><%= @content.content_field %></p>
  </div>
</section>