config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resources :locations, only: [ :show, :edit, :update, :destroy ]
  # resources :contents, only: [ :show, :edit, :update, :destroy ]
  # resources :images, only: [ :show, :edit, :update, :destroy ]

  # get '/' => 'locations#directory', :constraints => { :subdomain => 'locations' }, as: 'location_directory_subdomain'
  # get '/:id' => 'locations#show', :constraints => { :subdomain => "locations" }, as: 'location_subdomain'
  get '/:id' => 'locations#show', :constraints => { :subdomain => /^(?:(?!www).)*$/ }, as: 'location_subdomain'

  resources :brands, as: 'brands' do 

    resources :locations, as: 'locations', except: :show do
      collection do
        get '/import_export' => 'locations#import_export', as: "import_export"
        post :import
      end
    end

    resources :locations, as: 'locations', only: [:show], shallow: true

    resources :contents, as: 'contents'

    resources :images, as: 'images'

  end

  namespace :api do
    namespace :v1 do
      get '/brands' => 'brands#index'
      get '/brands/all' => 'brands#all'
      get '/locations' => 'locations#index'
      get '/images' => 'images#index'
      get '/contents' => 'contents#index'
    end
  end

  # get '/brands/:brand_id/locations' => 'locations#index', as: 'brand_location'
  # get '/brands/:brand_id/directory' => 'locations#directory', as: 'location_directory'
  # get '/brands/:brand_id/content' => 'contents#index', as: 'brand_content'
  # get '/brands/:brand_id/images' => 'images#index', as: 'brand_image'
  # get '/brands' => 'brands#index', as: 'brand'

  # get '/brands/:brand_id/locations/new' => 'locations#new', as: 'brand_location_new'
  # get '/brands/:brand_id/content/new' => 'contents#new', as: 'brand_content_new'
  # get '/brands/:brand_id/images/new' => 'images#new', as: 'brand_image_new'
  # get '/brands/new' => 'brands#new', as: 'brand_new'

  # post '/brands/:brand_id/locations' => 'locations#create'
  # post '/brands/:brand_id/content' => 'contents#create'
  # post '/brands/:brand_id/images' => 'images#create'
  # post '/brands' => 'brands#create', as: 'brand_create'

  # get '/brands/:brand_id/locations/:id' => 'locations#show', as: 'brand_location_show'
  # get '/brands/:brand_id/content/:id' => 'contents#show', as: 'brand_content_show'
  # get '/brands/:brand_id/images/:id' => 'images#show', as: 'brand_image_show'
  # get '/brands/:id' => 'brands#show', as: "brand_show"

  # get '/brands/:brand_id/locations/:id/edit' => 'locations#edit', as: 'brand_location_edit'
  # get '/brands/:brand_id/content/:id/edit' => 'contents#edit', as: 'brand_content_edit'
  # get '/brands/:brand_id/images/:id/edit' => 'images#edit', as: 'brand_image_edit'
  # get '/brands/:id/edit' => 'brands#edit', as: 'brand_edit'

  # patch '/brands/:brand_id/locations/:id' => 'locations#update', as: 'brand_location_update'
  # patch '/brands/:brand_id/content/:id' => 'contents#update', as: 'brand_content_update'
  # patch '/brands/:brand_id/images/:id' => 'images#update', as: 'brand_image_update'
  # patch '/brands/:id' => 'brands#update', as: 'brand_update'

  # delete '/brands/:brand_id/locations/:id' => 'locations#destroy', as: 'brand_location_delete'
  # delete '/brands/:brand_id/content/:id' => 'contents#destroy', as: 'brand_content_delete'
  # delete '/brands/:brand_id/images/:id' => 'images#destroy', as: 'brand_image_delete'
  # delete '/brands/:id' => 'brands#destroy', as: 'brand_delete'

  # Contact Email Page
  post '/contact' => 'pages#contact_email', as: 'contact_email'

  post '/:id' => 'locations#send_mail', as: 'location_send_email'

  #static pages
  root "pages#show", page: "home", as: 'home'
  get "/*page" => "pages#show"
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :brand_users
  has_many :users, through: :brand_users
  has_many :contents, as: :contentable
  has_many :images, as: :imageable
  has_many :locations

  validates :brand_name, :brand_address_1, :brand_city, :brand_state, :brand_zipcode, :brand_phone_number, :brand_url, :brand_subdomain, presence: true
  validates_uniqueness_of :brand_name

  def self.search(search)
    if Rails.env.production?
      where("brand_name ILIKE ? OR cast(brand_id as text) ILIKE ?", "%#{search}%", "%#{search}%")
    else
      where("brand_name LIKE ? OR brand_id LIKE ?", "%#{search}%", "%#{search}%") 
    end
  end

  def location_count
    locations.count
  end

  def brand_updated_at
    self.updated_at.strftime("%e %b %Y %I:%M%p")
  end

  def brand_created_at
    self.created_at.strftime("%e %b %Y %I:%M%p")
  end

  def brand_name_to_subdomain
    brand_name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
  end

end

app/controllers/api/v1/brands_controller.rb
class Api::V1::BrandsController < ApplicationController

  def index
    @brands = current_user.brands.all
  end

  def all
    @brands = Brand.all
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  
  before_action :authenticate_user!
  layout "cms_brands_layout"

  def index
    @brands = current_user.brands.all

    if params[:search]
      @brands = current_user.brands.search(params[:search])
    else
      @brands = current_user.brands.all
    end

    if params[:filter] && params[:filter_order]
        @brands = @brands.order(params[:filter] => params[:filter_order])
    end

  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new({ 
      brand_name: params[:brand_name],
      brand_address_1: params[:brand_address_1],
      brand_address_2: params[:brand_address_2],
      brand_city: params[:brand_city],
      brand_state: params[:brand_state],
      brand_zipcode: params[:brand_zipcode],
      brand_phone_number: params[:brand_phone_number],
      brand_industry: params[:brand_industry],
      brand_url: params[:brand_url],
      brand_subdomain: params[:brand_subdomain],
      primary_color: params[:primary_color],
      secondary_color: params[:secondary_color],
      tertiary_color: params[:tertiary_color],
      brand_tagline_title: params[:brand_tagline_title],
      brand_tagline_summary: params[:brand_tagline_summary],
      brand_meta_description: params[:brand_meta_description],
      brand_meta_keywords: params[:brand_meta_keywords],
      brand_meta_title: params[:brand_meta_title]
      })
 
    if @brand.save
      flash[:success] = "New Brand Created"

      branduser = BrandUser.new(user_id: current_user.id, brand_id: @brand.id)
      branduser.save

      redirect_to brands_path
    else
      render :new
    end
  end

  def show
    @brand = Brand.find(params[:id])

    redirect_to brands_path
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update({ 
      brand_name: params[:brand_name],
      brand_address_1: params[:brand_address_1],
      brand_address_2: params[:brand_address_2],
      brand_city: params[:brand_city],
      brand_state: params[:brand_state],
      brand_zipcode: params[:brand_zipcode],
      brand_phone_number: params[:brand_phone_number],
      brand_industry: params[:brand_industry],
      brand_url: params[:brand_url],
      brand_subdomain: params[:brand_subdomain],
      primary_color: params[:primary_color],
      secondary_color: params[:secondary_color],
      tertiary_color: params[:tertiary_color],
      brand_tagline_title: params[:brand_tagline_title],
      brand_tagline_summary: params[:brand_tagline_summary],
      brand_meta_description: params[:brand_meta_description],
      brand_meta_keywords: params[:brand_meta_keywords],
      brand_meta_title: params[:brand_meta_title]
      })
    
      flash[:info] = "Brand Updated"

      redirect_to brands_path
    else 
      render :edit
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    flash[:danger] = "Brand Deleted"

    redirect_to brands_path
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/edit.html.erb
<section class="section">  
  <div class="container">

    <% if @brand.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>
     
        <ul>
        <% @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-12">
      <h1>Edit Brand  <span style="display: inline-block; font-size: 24px;">: <%= @brand.brand_name %></span></h1>

      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a data-target="#brand-info" data-toggle="tab">Brand Information</a></li>
        <li><a data-target="#colors" data-toggle="tab">Brand Colors</a></li>
        <li><a data-target="#meta" data-toggle="tab">Meta Information</a></li>
        <li><a data-target="#dns" data-toggle="tab">DNS Settings</a></li>
      </ul>

      <%= form_tag brand_path, class: "form-group", method: :patch do %>
      
    <div class="tab-content">

    <div class="tab-pane active" id="brand-info"> 
      <div class="row">
      <div class="container">
       <!-- <div class="col-md-12"> -->
       <br>
       <h3>Brand Information</h3>
          <div class="col-md-12">
           <table class="table table-hover">
            <tbody>  
              <tr>
                <td>
                  <td><%= label_tag :name %></td>
                  <td><%= text_field_tag :brand_name, @brand.brand_name, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :address_1 %></td>
                  <td><%= text_field_tag :brand_address_1, @brand.brand_address_1, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :address_2 %></td>
                  <td><%= text_field_tag :brand_address_2, @brand.brand_address_2, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :city %></td>
                  <td><%= text_field_tag :brand_city, @brand.brand_city, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :state %></td>
                  <td><%= text_field_tag :brand_state, @brand.brand_state, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :zipcode %></td>
                  <td><%= text_field_tag :brand_zipcode, @brand.brand_zipcode, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :phone_number, "Phone Number" %></td>
                  <td><%= text_field_tag :brand_phone_number, @brand.brand_phone_number, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

      <div class="tab-pane" id="colors">
        <div class="row">
        <div class="container">
        <div class="col-md-12">
          <br>
          <h3>Brand Colors</h3>
          <br>
          <p>In order to better customize your location pages, please include three primary colors of your brand.</p>
          <br>

           <table class="table table-hover">
            <tbody>  
                <td>
                  <td><%= label_tag :primary_brand_color, "Primary Brand Color" %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Add a 6 digit hexidecimal value. Include the # character."><%= text_field_tag :primary_color, @brand.primary_color, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :secondary_brand_color, "Secondary Brand Color" %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Add a 6 digit hexidecimal value. Include the # character."><%= text_field_tag :secondary_color, @brand.secondary_color, class: "form-control" %></td>
                </td>
              </tr>
              
              <tr>
                <td>
                  <td><%= label_tag :tertiary_brand_color, "Tertiary Brand Color" %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Add a 6 digit hexidecimal value. Include the # character."><%= text_field_tag :tertiary_color, @brand.tertiary_color, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

      <div class="tab-pane" id="meta">
        <div class="row">
        <div class="container">
        <div class="col-md-12">
          <br>
          <h3>Meta Information</h3>
          <br>

           <table class="table table-hover">
            <tbody>  
              <tr>
                <td>
                  <td><%= label_tag :brand_tagline_title, 'Brand Tagline Title' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="This title appear in your brands directory page within the page promo image."><%= text_field_tag :brand_tagline_title, @brand.brand_tagline_title, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_tagline_summary, 'Brand Tagline Summary' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="This summary will appear in your brands directory page within the page promo image."><%= text_field_tag :brand_tagline_summary, @brand.brand_tagline_summary, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_meta_description, 'Brand Meta Description' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Any description will be included within your brands directory page under it's meta description tag."><%= text_area_tag :brand_meta_description, @brand.brand_meta_description, class: "form-control", size: "75x10" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_meta_keywords, 'Brand Meta Keywords' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Any keywords will be included within your brands directory page under it's meta keyword tag."><%= text_field_tag :brand_meta_keywords, @brand.brand_meta_keywords, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_meta_title, 'Brand Meta Title' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Any title will be included within your brands directory page under it's title tag."><%= text_field_tag :brand_meta_title, @brand.brand_meta_title, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

      <div class="tab-pane" id="dns">
        <div class="row">
        <div class="container">
        <div class="col-md-12">
          <br>
          <h3>DNS Settings</h3>
          <br>
          <p>Prior to adding your locations, please make sure your DNS routing is properly setup.</p>
          <br>
          <p>To setup your DNS routing, create a CNAME record with the subdomain of your choosing. Direct your new record to the DNS URL provided below.</p>
          <br>

           <table class="table table-hover">
            <tbody>  
              <tr>
                <td>
                  <td><%= label_tag :custom_dns_url, 'DNS URL' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Point your CNAME record to this URL."><p class="form-control">fierce-caverns-77919.herokuapp.com.</p></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_url, 'Brand URL' %></td>
                  <td data-toggle="tooltip" data-html="true" data-placement="bottom" title="Example: mybranddomain.com<br><br>Please enter only the bare domain. Do not include www. or http://"><%= text_field_tag :brand_url, @brand.brand_url, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_subdomain, 'Brand Subdomain' %></td>
                  <td data-toggle="tooltip" data-html="true" data-placement="bottom" title="Input the subdomain you plan to direct your locations to.<br><br>Example: locations"><%= text_field_tag :brand_subdomain, @brand.brand_subdomain, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

    </div>

      <div class="col-md-12">
        <%= submit_tag 'Update Brand', class: "btn btn-cta-cms-search btn-xs"%>
      </div>

      <% end %>
    </div>  
  </div>
</section>

app/views/brands/index.html.erb
<section class="section">  
  <div class="container">

    <!-- <div ng-app="app">
    <div ng-controller="brandsCtrl" ng-init="setup()"> -->
    <!-- {{ 1 + 1 }} -->
    <table class="table table-hover table-responsive">
        <thead>
          <tr>
            <th class="hidden-xs">ID</th>
            <th>Brand Name</th>
            <th class="hidden-xs hidden-sm">Total Locations</th>
            <th class="hidden-xs">Updated</th>
            <th class="hidden-xs">Created</th>
            <th>View</th> 
            <th>Edit</th>
            <th>Delete</th>  
          </tr>
        </thead>
        <tbody>
          <tr ng-repeat="brand in brands | filter: searchFilter | orderBy:sortByAttribute:descending">
            <td class="hidden-xs">{{ brand.id }}</td>
            <td>{{ brand.brand_name }}</td>
            <td class="hidden-xs hidden-sm">{{ brand.location_count }}</td>
            <td class="hidden-xs">{{ brand.updated_at }}</td>
            <td class="hidden-xs">{{ brand.created_at }}</td>
            <td>
              <% url_escaped_href = brand_locations_path('{{ brand.id}}') 
                brand_locations_path = URI::unescape(url_escaped_href)
              %>
              <a ng-href="<%= brand_locations_path %>" class="btn btn-cta-cms-view btn-xs">View</a>
            </td>
            <td>
              <% url_escaped_href = edit_brand_path('{{ brand.id}}') 
                edit_brand_path = URI::unescape(url_escaped_href)
              %>
              <a ng-href="<%= edit_brand_path %>" class="btn btn-cta-cms-view btn-xs">Edit</a>
            </td> 
            <td>
              <%= link_to "Delete", "/brands/{{brand.id}}", method: :delete, class: "btn btn-cta-cms-delete btn-xs", data: {confirm: "Are you sure?"}  %>
            </td>  
          </tr>
        </tbody>
    </table>

  </div>
</section>

app/views/brands/new.html.erb
<section class="section">  
  <div class="container">

    <% if @brand.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>
     
        <ul>
        <% @brand.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-12">
      <h1>Add Brand</h1>

      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a data-target="#brand-info" data-toggle="tab">Brand Information</a></li>
        <li><a data-target="#colors" data-toggle="tab">Brand Colors</a></li>
        <li><a data-target="#meta" data-toggle="tab">Meta Information</a></li>
        <li><a data-target="#dns" data-toggle="tab">DNS Settings</a></li>
      </ul>

      <%= form_tag brands_path, class: "form-group", method: :post do %>
      
    <div class="tab-content">

    <div class="tab-pane active" id="brand-info"> 
      <div class="row">
      <div class="container">
       <!-- <div class="col-md-12"> -->
       <br>
       <h3>Brand Information</h3>
          <div class="col-md-12">
           <table class="table table-hover">
            <tbody>  
              <tr>
                <td>
                  <td><%= label_tag :name %></td>
                  <td><%= text_field_tag :brand_name, @brand.brand_name, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :address_1 %></td>
                  <td><%= text_field_tag :brand_address_1, @brand.brand_address_1, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :address_2 %></td>
                  <td><%= text_field_tag :brand_address_2, @brand.brand_address_2, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :city %></td>
                  <td><%= text_field_tag :brand_city, @brand.brand_city, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :state %></td>
                  <td><%= text_field_tag :brand_state, @brand.brand_state, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :zipcode %></td>
                  <td><%= text_field_tag :brand_zipcode, @brand.brand_zipcode, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :phone_number, "Phone Number" %></td>
                  <td><%= text_field_tag :brand_phone_number, @brand.brand_phone_number, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

      <div class="tab-pane" id="colors">
        <div class="row">
        <div class="container">
        <div class="col-md-12">
          <br>
          <h3>Brand Colors</h3>
          <br>
          <p>In order to better customize your location pages, please include three primary colors of your brand.</p>
          <br>

           <table class="table table-hover">
            <tbody>  
                <td>
                  <td><%= label_tag :primary_brand_color, "Primary Brand Color" %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Add a 6 digit hexidecimal value. Include the # character."><%= text_field_tag :primary_color, @brand.primary_color, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :secondary_brand_color, "Secondary Brand Color" %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Add a 6 digit hexidecimal value. Include the # character."><%= text_field_tag :secondary_color, @brand.secondary_color, class: "form-control" %></td>
                </td>
              </tr>
              
              <tr>
                <td>
                  <td><%= label_tag :tertiary_brand_color, "Tertiary Brand Color" %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Add a 6 digit hexidecimal value. Include the # character."><%= text_field_tag :tertiary_color, @brand.tertiary_color, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

      <div class="tab-pane" id="meta">
        <div class="row">
        <div class="container">
        <div class="col-md-12">
          <br>
          <h3>Meta Information</h3>
          <br>

           <table class="table table-hover">
            <tbody>  
              <tr>
                <td>
                  <td><%= label_tag :brand_tagline_title, 'Brand Tagline Title' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="This title appear in your brands directory page within the page promo image."><%= text_field_tag :brand_tagline_title, @brand.brand_tagline_title, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_tagline_summary, 'Brand Tagline Summary' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="This summary will appear in your brands directory page within the page promo image."><%= text_field_tag :brand_tagline_summary, @brand.brand_tagline_summary, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_meta_description, 'Brand Meta Description' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Any description will be included within your brands directory page under it's meta description tag."><%= text_area_tag :brand_meta_description, @brand.brand_meta_description, class: "form-control", size: "75x10" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_meta_keywords, 'Brand Meta Keywords' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Any keywords will be included within your brands directory page under it's meta keyword tag."><%= text_field_tag :brand_meta_keywords, @brand.brand_meta_keywords, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_meta_title, 'Brand Meta Title' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Any title will be included within your brands directory page under it's title tag."><%= text_field_tag :brand_meta_title, @brand.brand_meta_title, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>

      <div class="tab-pane" id="dns">
        <div class="row">
        <div class="container">
        <div class="col-md-12">
          <br>
          <h3>DNS Settings</h3>
          <br>
          <p>Prior to adding your locations, please make sure your DNS routing is properly setup.</p>
          <br>
          <p>To setup your DNS routing, create a CNAME record with the subdomain of your choosing. Direct your new record to the DNS URL provided below.</p>
          <br>

           <table class="table table-hover">
            <tbody>  
              <tr>
                <td>
                  <td><%= label_tag :custom_dns_url, 'DNS URL' %></td>
                  <td data-toggle="tooltip" data-placement="bottom" title="Point your CNAME record to this URL."><p class="form-control">fierce-caverns-77919.herokuapp.com.</p></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_url, 'Brand URL' %></td>
                  <td data-toggle="tooltip" data-html="true" data-placement="bottom" title="Example: mybranddomain.com<br><br>Please enter only the bare domain. Do not include www. or http://"><%= text_field_tag :brand_url, @brand.brand_url, class: "form-control" %></td>
                </td>
              </tr>
              <tr>
                <td>
                  <td><%= label_tag :brand_subdomain, 'Brand Subdomain' %></td>
                  <td data-toggle="tooltip" data-html="true" data-placement="bottom" title="Input the subdomain you plan to direct your locations to.<br><br>Example: locations"><%= text_field_tag :brand_subdomain, @brand.brand_subdomain, class: "form-control" %></td>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      </div>
      </div>
    </div>

      <div class="col-md-12">
        <%= submit_tag 'Add Brand', class: "btn btn-cta-cms-search btn-xs"%>
      </div>

      <% end %>
    </div>  
  </div>
</section>