config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resources :locations, only: [ :show, :edit, :update, :destroy ]
  # resources :contents, only: [ :show, :edit, :update, :destroy ]
  # resources :images, only: [ :show, :edit, :update, :destroy ]

  # get '/' => 'locations#directory', :constraints => { :subdomain => 'locations' }, as: 'location_directory_subdomain'
  # get '/:id' => 'locations#show', :constraints => { :subdomain => "locations" }, as: 'location_subdomain'
  get '/:id' => 'locations#show', :constraints => { :subdomain => /^(?:(?!www).)*$/ }, as: 'location_subdomain'

  resources :brands, as: 'brands' do 

    resources :locations, as: 'locations', except: :show do
      collection do
        get '/import_export' => 'locations#import_export', as: "import_export"
        post :import
      end
    end

    resources :locations, as: 'locations', only: [:show], shallow: true

    resources :contents, as: 'contents'

    resources :images, as: 'images'

  end

  namespace :api do
    namespace :v1 do
      get '/brands' => 'brands#index'
      get '/brands/all' => 'brands#all'
      get '/locations' => 'locations#index'
      get '/images' => 'images#index'
      get '/contents' => 'contents#index'
    end
  end

  # get '/brands/:brand_id/locations' => 'locations#index', as: 'brand_location'
  # get '/brands/:brand_id/directory' => 'locations#directory', as: 'location_directory'
  # get '/brands/:brand_id/content' => 'contents#index', as: 'brand_content'
  # get '/brands/:brand_id/images' => 'images#index', as: 'brand_image'
  # get '/brands' => 'brands#index', as: 'brand'

  # get '/brands/:brand_id/locations/new' => 'locations#new', as: 'brand_location_new'
  # get '/brands/:brand_id/content/new' => 'contents#new', as: 'brand_content_new'
  # get '/brands/:brand_id/images/new' => 'images#new', as: 'brand_image_new'
  # get '/brands/new' => 'brands#new', as: 'brand_new'

  # post '/brands/:brand_id/locations' => 'locations#create'
  # post '/brands/:brand_id/content' => 'contents#create'
  # post '/brands/:brand_id/images' => 'images#create'
  # post '/brands' => 'brands#create', as: 'brand_create'

  # get '/brands/:brand_id/locations/:id' => 'locations#show', as: 'brand_location_show'
  # get '/brands/:brand_id/content/:id' => 'contents#show', as: 'brand_content_show'
  # get '/brands/:brand_id/images/:id' => 'images#show', as: 'brand_image_show'
  # get '/brands/:id' => 'brands#show', as: "brand_show"

  # get '/brands/:brand_id/locations/:id/edit' => 'locations#edit', as: 'brand_location_edit'
  # get '/brands/:brand_id/content/:id/edit' => 'contents#edit', as: 'brand_content_edit'
  # get '/brands/:brand_id/images/:id/edit' => 'images#edit', as: 'brand_image_edit'
  # get '/brands/:id/edit' => 'brands#edit', as: 'brand_edit'

  # patch '/brands/:brand_id/locations/:id' => 'locations#update', as: 'brand_location_update'
  # patch '/brands/:brand_id/content/:id' => 'contents#update', as: 'brand_content_update'
  # patch '/brands/:brand_id/images/:id' => 'images#update', as: 'brand_image_update'
  # patch '/brands/:id' => 'brands#update', as: 'brand_update'

  # delete '/brands/:brand_id/locations/:id' => 'locations#destroy', as: 'brand_location_delete'
  # delete '/brands/:brand_id/content/:id' => 'contents#destroy', as: 'brand_content_delete'
  # delete '/brands/:brand_id/images/:id' => 'images#destroy', as: 'brand_image_delete'
  # delete '/brands/:id' => 'brands#destroy', as: 'brand_delete'

  # Contact Email Page
  post '/contact' => 'pages#contact_email', as: 'contact_email'

  post '/:id' => 'locations#send_mail', as: 'location_send_email'

  #static pages
  root "pages#show", page: "home", as: 'home'
  get "/*page" => "pages#show"
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :brand
  has_many :images, as: :imageable
  has_many :contents, as: :contentable

  geocoded_by :full_address
  after_validation :geocode

  extend FriendlyId
  friendly_id :meta_url, use: [:slugged, :finders]

  validates :business_name, :address_1, :city, :state, :zipcode, :phone_number, presence: true

  def self.search(search)
    if Rails.env.production?
      where("business_name ILIKE ? OR cast(id as text) ILIKE ?", "%#{search}%", "%#{search}%")
    else
      where("business_name LIKE ? OR id LIKE ?", "%#{search}%", "%#{search}%") 
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |location|
        csv << location.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      location_hash = row.to_hash # exclude the price field
      location = Location.where(id: location_hash["id"])

      if location.count == 1
        location.first.update_attributes(location_hash)
      else
        Location.create!(location_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end

  def location_updated_at
    self.updated_at.strftime("%e %b %Y %I:%M%p")
  end

  def location_created_at
    self.created_at.strftime("%e %b %Y %I:%M%p")
  end

  def full_address
    "#{address_1}, #{city}, #{state} #{zipcode}"
  end
end

app/controllers/api/v1/locations_controller.rb
class Api::V1::LocationsController < ApplicationController

  def index
    @locations = current_user.brands.find(params[:brand_id]).locations
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :load_brand, :except => [:show, :send_mail]
  before_action :authenticate_user!, :only => [:index, :directory, :new, :create, :edit, :update, :destroy]
  # before_action :restrict_location_pages, :only => :show
  layout "cms_locations_layout", except: :show

  def index

    @searchPlaceholder = "Search Locations"

    if current_user.brands.exists?(params[:brand_id])
      # @locations = @brand.locations.all
      
      @locations = @brand.locations

      if params[:search]
        @locations = @brand.locations.search(params[:search])
      else
        @locations.all
      end

      if params[:filter] && params[:filter_order]
        @locations = @locations.order(params[:filter] => params[:filter_order])
      end
    else
      redirect_to "/"
      # redirect_to "locations.<%= @brand.brand_url %>/directory
    end

    respond_to do |format|
      format.html
      format.csv { send_data @locations.to_csv }
      # format.xls { send_data @locations.to_csv(col_sep: "\t") }
    end

  end

  def import
    @import = Location.import(params[:file])

    flash[:success] = "Locations imported."

    redirect_to brand_locations_path
  end

  def import_export

  end

  # def directory
    
  # end

  def new
    @location = Location.new
  end
  
  def create

    @location = @brand.locations.new({ 
      business_name: params[:business_name],
      address_1: params[:address_1],
      address_2: params[:address_2],
      city: params[:city],
      state: params[:state],
      zipcode: params[:zipcode],
      email: params[:email],
      phone_number: params[:phone_number],
      hours_of_operation: params[:hours_of_operation],
      business_description: params[:business_description],
      service_description: params[:service_description],
      areas_served: params[:areas_served],
      zipcodes_served: params[:zipcodes_served],
      languages: params[:languages],
      meta_description: params[:meta_description],
      meta_keywords: params[:meta_keywords],
      meta_title: params[:meta_title],
      meta_url: params[:meta_url],
      tagline_title: params[:tagline_title],
      tagline_summary: params[:tagline_summary]
      })

    if @location.save
    
      flash[:success] = "New Location Created"

      redirect_to brand_locations_path

    else
      render :new
    end
  end

  def show
    if params[:id] == "directory"
      # @locations = Location.friendly.find(params[:id]).brands.locations.all
      @brand = Brand.find_by(brand_url: request.domain)

      if @brand
        @locations = Hash[@brand.locations.all.group_by(&:state).map{|k,v| [k, v.group_by(&:city)]}]

        render layout: "directory"
      end
    else
      @location = Location.friendly.find(params[:id])

      if request.domain != @location.brand.brand_url
        render :file => "#{Rails.root}/public/404.html",  :status => 404
      else
        render :layout => 'webpage'
      end

    end
  end

  def edit

    @location = Location.find(params[:id])
    # @location = Location.find(params[:brand_id])
  end

  def update

    @location = @brand.locations.find(params[:id])

    @location.update({ 
      business_name: params[:business_name],
      address_1: params[:address_1],
      address_2: params[:address_2],
      city: params[:city],
      state: params[:state],
      zipcode: params[:zipcode],
      email: params[:email],
      phone_number: params[:phone_number],
      hours_of_operation: params[:hours_of_operation],
      business_description: params[:business_description],
      service_description: params[:service_description],
      areas_served: params[:areas_served],
      zipcodes_served: params[:zipcodes_served],
      languages: params[:languages],
      meta_description: params[:meta_description],
      meta_keywords: params[:meta_keywords],
      meta_title: params[:meta_title],
      meta_url: params[:meta_url],
      tagline_title: params[:tagline_title],
      tagline_summary: params[:tagline_summary],
      slug: params[:slug]
      })

    # update location image
    if @location.images.first != nil
      @location.images.first.update( 
        image_name: "Location",
        image_category: "location",
        image: params[:image]
        # image_path: params[:image_path]
      )
    else
      @location.images.create( 
         image_name: params[:image_name],
         image_category: params[:image_category],
         image: params[:image]
         # image_path: params[:image_path]
       )
    end

    flash[:info] = "Location Updated"

    redirect_to brand_locations_path
  end

  def destroy

    @location = @brand.locations.find(params[:id])
    @location.destroy

    flash[:danger] = "Location Deleted"

    redirect_to brand_locations_path
  end

  def send_mail

    @location = Location.find(params[:id])

    name = params[:name]
    email = params[:email]
    body = params[:comments]
    location_email = params[:location_email]

    LocationPageMailer.welcome_email(name, email, body, location_email).deliver

    flash[:success] = "Message sent"

    if @location.slug
      redirect_to "/#{@location.slug}"
    else
      redirect_to "/#{@location.id}"
    end
  end

  private

  def load_brand
    @brand = Brand.find(params[:brand_id])
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/edit.html.erb
<section class="section">  
  <div class="container">

    <div class="col-md-12">
      <h1>Edit Location  <span class="edit-name">: <%= @location.business_name %></span></h1>

      <div class="progress" role="progressbar">
          <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" id="bar"></div>
      </div>

      <!-- <ul class="nav nav-tabs">
        <li role="presentation"><a href="#local">Local</a></li>
        <li role="presentation"><a href="#about">About</a></li>
        <li role="presentation"><a href="#meta">Meta</a></li>
      </ul> -->

      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a data-target="#local" data-toggle="tab">Location Information</a></li>
        <li><a data-target="#about" data-toggle="tab">About</a></li>
        <li><a data-target="#meta" data-toggle="tab">Meta Information</a></li>
      </ul>

      <%= form_tag brand_location_path, multipart: true, class: "form-group", method: :patch do %>
      
      <div class="tab-content">

      <div class="tab-pane active" id="local">
      <div class="row">
        <div class="col-md-12">
        <br>
        <% if @location.images.first != nil %>  
          <% if @location.images.first.image_path.nil? %>
            <img src="<%= @location.images.first.image.thumb %>">
          <% else %>
            <%= image_tag @location.images.first.image_path, heigth: '100', width: '100' %>
          <% end %>
        <% end %>
        <br>
        <h3>Location Information</h3>
          <div class="col-md-6">
            <table class="table table-hover">
              <tbody>
                <tr>
                  <td><%= label_tag :image, "Upload an image" %></td>
                  <td><%= file_field_tag :image, class: "file-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :business_name %></td>
                  <td><%= text_field_tag :business_name, @location.business_name, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :street_address_1 %></td>
                  <td><%= text_field_tag :address_1, @location.address_1, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :street_address_2 %></td>
                  <td><%= text_field_tag :address_2, @location.address_2, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :city %></td>
                  <td><%= text_field_tag :city, @location.city, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :state %></td>
                  <td><%= text_field_tag :state, @location.state, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :zipcode %></td>
                  <td><%= text_field_tag :zipcode, @location.zipcode, class: "form-control" %></td>
                </tr>
              </tbody>
            </table>
          </div>

          <div class="col-md-6">
            <table class="table table-hover">
              <tbody>  
                <tr>
                  <td><%= label_tag :email %></td>
                  <td><%= text_field_tag :email, @location.email, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :phone_number %></td>
                  <td><%= text_field_tag :phone_number, @location.phone_number, class: "form-control" %></td>
                </tr>
                <tr>
                  <td><%= label_tag :hours_of_operation %></td>
                  <td data-toggle="tooltip" data-html="true" data-placement="bottom" title="Proper Hours Formatting:<br><br>List out your hours from Mon-Sun, seperating each day by semicolons.<br><br> 9:00am-5:00pm;9:00am-5:00pm;9:00am-5:00pm;9:00am-5:00pm;9:00am-5:00pm;Closed;Closed"><%= text_area_tag :hours_of_operation, @location.hours_of_operation, class: "form-control", size: "75x5" %></td>
                </tr>
              </tbody>
            </table>
          </div>
          </div>
        </div>
      </div>
        
      <div class="tab-pane" id="about">
      <div class="row">
        <div class="col-md-12"> 
        <br>
        <h3>About</h3>
        <table class="table table-hover">
          <tbody>  
            <tr>
                <td><%= label_tag :business_description %></td>
                <td><%= text_area_tag :business_description, @location.business_description, size: "75x10", class: "form-control" %></td>
            </tr>

            <tr>
                <td><%= label_tag :service_description %></td>
                <td><%= text_area_tag :service_description, @location.service_description, size: "75x10", class: "form-control" %></td>
            </tr>

            <tr>
                  <td><%= label_tag :areas_served %></td>
                  <td><%= text_field_tag :areas_served, @location.areas_served, size: "75x10", class: "form-control" %></td>
            </tr>

            <tr>
                  <td><%= label_tag :zipcodes_served %></td>
                  <td><%= text_field_tag :zipcodes_served, @location.zipcodes_served, size: "75x10", class: "form-control" %></td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>
      </div>

      <div class="tab-pane" id="meta">
      <div class="row">
        <div class="col-md-12">
        <br>
        <h3>Meta Information</h3>
        <table class="table table-hover">
          <tbody>  
            <tr>
              <td><%= label_tag :meta_url, "Custom Location URL" %></td>
              <td><%= text_field_tag :meta_url, @location.meta_url, size: "75x10", class: "form-control" %></td>
            </tr>
            <tr>
                <td><%= label_tag :tagline_title %></td>
                <td><%= text_field_tag :tagline_title, @location.tagline_title, size: "75x10", class: "form-control" %></td>
            </tr>
            <tr>
                <td><%= label_tag :tagline_summary %></td>
                <td><%= text_field_tag :tagline_summary, @location.tagline_summary, size: "75x10", class: "form-control" %></td>
            </tr>
            <tr>
              <td><%= label_tag :meta_description %></td>
              <td><%= text_area_tag :meta_description, @location.meta_description, size: "75x10", class: "form-control"  %></td>
            </tr>

            <tr>
              <td><%= label_tag :meta_keywords %></td>
              <td><%= text_area_tag :meta_keywords, @location.meta_keywords, size: "75x10", class: "form-control" %></td>
            </tr>

            <tr>
              <td><%= label_tag :meta_title %></td>
              <td><%= text_field_tag :meta_title, @location.meta_title, size: "75x10", class: "form-control" %></td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>
      </div>

      </div>

      <%= submit_tag 'Update Location', class: "btn btn-cta-cms-search btn-xs" %>

      <% end %>
    </div>  
  </div>
</section>

app/views/locations/import_export.erb
<section class="section">  
  <div class="container">

    <div class="col-md-12">
      <h1>Import/Export Locations</h1>

      <p>A CSV file can be used to import records. The first row should be the column name. The following columns are allowed.</p>
      <ul>
        <li><strong>id</strong> - Integer type</li>
        <li><strong>business_name</strong> - String type</li>
        <li><strong>address_1</strong> - String type</li>
        <li><strong>address_2</strong> - String type</li>
        <li><strong>city</strong> - String type</li>
        <li><strong>state</strong> - String type</li>
        <li><strong>zipcode</strong> - String type</li>
        <li><strong>hours_of_operation</strong> - String type</li>
        <li><strong>business_description</strong> - String type</li>
        <li><strong>service_description</strong> - String type</li>
        <li><strong>areas_served</strong> - String type</li>
        <li><strong>zipcodes_served</strong> - String type</li>
        <li><strong>languages</strong> - String type</li>
        <li><strong>meta_description</strong> - String type</li>
        <li><strong>meta_keywords</strong> - String type</li>
        <li><strong>meta_title</strong> - String type</li>
        <li><strong>meta_url</strong> - String type</li>
        <li><strong>phone_number</strong> - String type</li>
        <li><strong>brand_id</strong> - Integer type</li>
        <li><strong>type</strong> - String type</li>
        <li><strong>latitude</strong> - Integer type</li>
        <li><strong>longitude</strong> - Integer type</li>
        <li><strong>tagline_title</strong> - String type</li>
        <li><strong>tagline_summary</strong> - String type</li>
        <li><strong>email</strong> - String type</li>
        <li><strong>slug</strong> - String type</li>

                              
      </ul>
      <p>If an <strong>id</strong> is supplied, it will update the existing record instead of creating a new one.</p>
      <br>
      <p>You can download a list of your existing locations below.</p>
      <%= link_to "Download Locations CSV", brand_locations_path(format: "csv") %>
      <br>
      <br>

      <%= form_tag import_brand_locations_path, multipart: true, method: :post do %>
        <%= file_field_tag :file, class: "file-control" %>
        <br>

      <%= submit_tag 'Import Locations', class: "btn btn-cta-cms-search btn-xs"%>

      <% end %>

    </div>  
  </div>
</section>

app/views/locations/index.html.erb
<script>
  window.brandId = <%= @locations.first.brand.id unless @locations.first.blank? %>
</script>

<section class="section">  
  <div class="container">

    <table class="table table-hover table-responsive">
      <thead>
        <tr>
          <th class="hidden-xs">ID</th>
          <th>Location Name</th>
          <th class="hidden-xs hidden-sm">City</th>
          <th class="hidden-xs hidden-sm">State</th>
          <th class="hidden-xs">Updated</th>
          <th class="hidden-xs">Created</th>
          <th>View</th> 
          <th>Edit</th>
          <th>Delete</th>  
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="location in locations | filter: searchFilter | orderBy:sortByAttribute:descending">
          <td class="hidden-xs">{{ location.id }}</td>
          <td>{{ location.business_name }}</td>
          <td class="hidden-xs hidden-sm">{{ location.city }}</td>
          <td class="hidden-xs hidden-sm">{{ location.state }}</td>
          <td class="hidden-xs">{{ location.updated_at }}</td>
          <td class="hidden-xs">{{ location.created_at }}</td>
          <td>
            <div ng-hide="location.slug">
              <a ng-href="http://{{ location.brand_subdomain }}.{{ location.brand_url }}/{{ location.id }}" class="btn btn-cta-cms-view btn-xs" target="_blank">View</a>
            </div>
            <div ng-hide="!location.slug">
              <a ng-href="http://{{ location.brand_subdomain }}.{{ location.brand_url }}/{{ location.slug }}" class="btn btn-cta-cms-view btn-xs" target="_blank">View</a>
            </div>
          </td>
          <td>
            <% url_escaped_href = edit_brand_location_path('{{ location.brand_id }}','{{ location.id }}') 
              edit_brand_location_path = URI::unescape(url_escaped_href)
            %>
            <a ng-href="<%= edit_brand_location_path %>" class="btn btn-cta-cms-view btn-xs">Edit</a>
          </td> 
          <td>
            <%= link_to "Delete", "/brands/{{ location.brand_id }}/locations/{{ location.id }}", method: :delete, class: "btn btn-cta-cms-delete btn-xs", data: {confirm: "Are you sure?"}  %>
          </td>  
        </tr>
      </tbody>
    </table>
  </div>
</section>

app/views/locations/new.html.erb
<section class="section">  
  <div class="container">

    <% if @location.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>
     
        <ul>
        <% @location.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-12">
      <h1>Add Location</h1>

      <%= form_tag brand_locations_path, class: "form-group", method: :post do %>

        <div class="col-md-6">
          <table class="table table-hover">
            <tbody>
              <tr>
                <td><%= label_tag :business_name %></td>
                <td><%= text_field_tag :business_name, @location.business_name, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :street_address_1 %></td>
                <td><%= text_field_tag :address_1, @location.address_1, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :street_address_2 %></td>
                <td><%= text_field_tag :address_2, @location.address_2, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :city %></td>
                <td><%= text_field_tag :city, @location.city, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :state %></td>
                <td><%= text_field_tag :state, @location.state, class: "form-control" %></td>
              </tr>
              <tr>
                <td><%= label_tag :zipcode %></td>
                <td><%= text_field_tag :zipcode, @location.zipcode, class: "form-control" %></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="col-md-6">
          <table class="table table-hover">
            <tbody>  
              <tr>
                <td><%= label_tag :phone_number %></td>
                <td><%= text_field_tag :phone_number, @location.phone_number, class: "form-control" %></td>
              </tr>
            </tbody>
          </table>
        </div>


      <div class="col-md-12">
        <%= submit_tag 'Add Location', class: "btn btn-cta-cms-search btn-xs" %>
      </div>

      <% end %>
    </div>  
  </div>
</section>