config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # resources :locations, only: [ :show, :edit, :update, :destroy ]
  # resources :contents, only: [ :show, :edit, :update, :destroy ]
  # resources :images, only: [ :show, :edit, :update, :destroy ]

  # get '/' => 'locations#directory', :constraints => { :subdomain => 'locations' }, as: 'location_directory_subdomain'
  # get '/:id' => 'locations#show', :constraints => { :subdomain => "locations" }, as: 'location_subdomain'
  get '/:id' => 'locations#show', :constraints => { :subdomain => /^(?:(?!www).)*$/ }, as: 'location_subdomain'

  resources :brands, as: 'brands' do 

    resources :locations, as: 'locations', except: :show do
      collection do
        get '/import_export' => 'locations#import_export', as: "import_export"
        post :import
      end
    end

    resources :locations, as: 'locations', only: [:show], shallow: true

    resources :contents, as: 'contents'

    resources :images, as: 'images'

  end

  namespace :api do
    namespace :v1 do
      get '/brands' => 'brands#index'
      get '/brands/all' => 'brands#all'
      get '/locations' => 'locations#index'
      get '/images' => 'images#index'
      get '/contents' => 'contents#index'
    end
  end

  # get '/brands/:brand_id/locations' => 'locations#index', as: 'brand_location'
  # get '/brands/:brand_id/directory' => 'locations#directory', as: 'location_directory'
  # get '/brands/:brand_id/content' => 'contents#index', as: 'brand_content'
  # get '/brands/:brand_id/images' => 'images#index', as: 'brand_image'
  # get '/brands' => 'brands#index', as: 'brand'

  # get '/brands/:brand_id/locations/new' => 'locations#new', as: 'brand_location_new'
  # get '/brands/:brand_id/content/new' => 'contents#new', as: 'brand_content_new'
  # get '/brands/:brand_id/images/new' => 'images#new', as: 'brand_image_new'
  # get '/brands/new' => 'brands#new', as: 'brand_new'

  # post '/brands/:brand_id/locations' => 'locations#create'
  # post '/brands/:brand_id/content' => 'contents#create'
  # post '/brands/:brand_id/images' => 'images#create'
  # post '/brands' => 'brands#create', as: 'brand_create'

  # get '/brands/:brand_id/locations/:id' => 'locations#show', as: 'brand_location_show'
  # get '/brands/:brand_id/content/:id' => 'contents#show', as: 'brand_content_show'
  # get '/brands/:brand_id/images/:id' => 'images#show', as: 'brand_image_show'
  # get '/brands/:id' => 'brands#show', as: "brand_show"

  # get '/brands/:brand_id/locations/:id/edit' => 'locations#edit', as: 'brand_location_edit'
  # get '/brands/:brand_id/content/:id/edit' => 'contents#edit', as: 'brand_content_edit'
  # get '/brands/:brand_id/images/:id/edit' => 'images#edit', as: 'brand_image_edit'
  # get '/brands/:id/edit' => 'brands#edit', as: 'brand_edit'

  # patch '/brands/:brand_id/locations/:id' => 'locations#update', as: 'brand_location_update'
  # patch '/brands/:brand_id/content/:id' => 'contents#update', as: 'brand_content_update'
  # patch '/brands/:brand_id/images/:id' => 'images#update', as: 'brand_image_update'
  # patch '/brands/:id' => 'brands#update', as: 'brand_update'

  # delete '/brands/:brand_id/locations/:id' => 'locations#destroy', as: 'brand_location_delete'
  # delete '/brands/:brand_id/content/:id' => 'contents#destroy', as: 'brand_content_delete'
  # delete '/brands/:brand_id/images/:id' => 'images#destroy', as: 'brand_image_delete'
  # delete '/brands/:id' => 'brands#destroy', as: 'brand_delete'

  # Contact Email Page
  post '/contact' => 'pages#contact_email', as: 'contact_email'

  post '/:id' => 'locations#send_mail', as: 'location_send_email'

  #static pages
  root "pages#show", page: "home", as: 'home'
  get "/*page" => "pages#show"
end

app/views/layouts/cms_brands_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= site_name %> | Brands</title>
  <%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
</head>
<body>
  <div ng-app="app">
  <div ng-controller="brandsCtrl" ng-init="setup()">

  <header id="header-cms" class="header">  
      <div class="container">            
          <h1 class="logo pull-left">
              <a href="/brands">
                  <span class="logo-title">Brands</span>
              </a>
          </h1><!--//logo-->              
          <nav id="main-nav" class="main-nav navbar-right" role="navigation">
              <div class="navbar-header">
                  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button><!--//nav-toggle-->
              </div><!--//navbar-header-->            
              <div class="navbar-collapse collapse" id="navbar-collapse">
                  <ul class="nav navbar-nav">                         

                  <% if current_page?(brands_path) %>
                    <li>  
                      <input class="form-control hidden-xs hidden-sm" placeholder="Search Brands" ng-model="searchFilter">
                    </li>
                  <% end %>

                    <li class="nav-item"><%= link_to "Sign Out", "/users/sign_out", method: :delete if user_signed_in? %></li>

                  </ul><!--//nav-->
              </div><!--//navabr-collapse-->
          </nav><!--//main-nav-->           
      </div><!--//container-->

      <div class="filter-cms-bar ">
        <div class="container">
            <div class="row">
              <div class="col-md-12">

              <% if current_page?(brands_path(@brand)) %>
                <div class="btn-group">
                  <button class="btn btn-cta-cms btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('brand_name')">
                    Filter by Name <span class="caret"></span>
                  </button>
                </div>

                <div class="btn-group">
                  <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('updated_at')">
                    Filter by Updated At <span class="caret"></span>
                  </button>
                </div>

                <div class="btn-group">
                  <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('created_at')">
                    Filter by Created At <span class="caret"></span>
                  </button>
                </div>

                <%= link_to "Add new brand", "/brands/new", class: "btn btn-cta-cms btn-xs pull-right" %>

                <br>
                <br>
                <input class="form-control visible-xs visible-sm" placeholder="Search Brands" ng-model="searchFilter">
              <% end %>

            </div>
          </div>
        </div>
      </div>

  </header><!--//header-->

  <div class="container">
    <% flash.each do |name, message| %>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
  </div>

  <%= yield %>

  <!-- ******FOOTER****** --> 
  <div class="bottom-cms-bar">
      <div class="container">
          <div class="row">
              <small class="copyright col-md-6 col-sm-6 col-xs-12">Copyright @ <%= Time.now.year %> <a href="#"><%= site_name %></a></small>
          </div><!--//row-->
      </div><!--//container-->
  </div><!--//bottom-bar-->

  </div><!-- NG-CONTROLLER END -->
  </div><!-- NG-APP END -->

</body>
</html>

app/views/layouts/cms_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmsLocationApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="dashboard">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobilenav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/locations">LocationZ</a>
      </div>

      <div class="collapse navbar-collapse" id="mobilenav">
        <ul class="nav navbar-nav">
          <li><a href="/locations">Locations</a></li>
          <li><a href="/images">Images</a></li>
          <li><a href="/content">Content</a></li>
          <li><a href="/brand">Brand</a></li>
          <li><a href="/users">Users</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign In", "/users/sign_in", method: :get if !user_signed_in? %></li>
          <li><%= link_to "Sign Out", "/users/sign_out", method: :delete if user_signed_in? %></li>
        </ul>

        <%= form_tag "/search", class: "navbar-form navbar-right" do %>
          <%= text_field_tag :search, nil, placeholder: "Search Locations", class: "form-control" %>
          <%= submit_tag "Search", class: "btn btn-default" %>
        <% end %>

        

      </div><!-- /.navbar-collapse -->

    </div><!-- /.container -->
  </nav>

  <div class="container">

    <% flash.each do |name, message| %>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>

    <div class="row">
        <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/cms_locations_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @brand.brand_name %> | Locations</title>
  <%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
</head>
<body>

  <div ng-app="app">
  <% if current_page?(brand_locations_path(@brand.id)) %>  
    <div ng-controller="locationsCtrl" ng-init="setup()">
  <% elsif current_page?(brand_images_path(@brand.id)) %>
    <div ng-controller="imagesCtrl" ng-init="setup()">
  <% elsif current_page?(brand_contents_path(@brand.id)) %>
    <div ng-controller="contentsCtrl" ng-init="setup()">
  <% end %>

  <header id="header" class="cms header">  
      <div class="container">            
          <h1 class="logo pull-left">
              <a href="<%= brand_locations_path(@brand.id) %>">
                  <% if @brand.images.where(image_category: 'logo').take %>  
                    <span class="logo-title brand-logo"><img src="<%= @brand.images.where(image_category: 'logo').first.image.logo %>"></span>
                  <% else %>
                    <span class="logo-title"><%= @brand.brand_name %></span>
                  <% end %>
              </a>
          </h1><!--//logo-->              
          <nav id="main-nav" class="main-nav navbar-right" role="navigation">
              <div class="navbar-header">
                  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button><!--//nav-toggle-->
              </div><!--//navbar-header-->            
              <div class="navbar-collapse collapse" id="navbar-collapse">
                  <ul class="nav navbar-nav"> 
                    <li class="nav-item"><a href="<%= brands_path %>">Brands</a></li>
                    <li class="nav-item"><a href="<%= brand_locations_path(@brand.id) %>">Locations</a></li>
                    <li class="nav-item"><a href="<%= brand_images_path(@brand.id) %>">Images</a></li>
                    <li class="nav-item"><a href="<%= brand_contents_path(@brand.id) %>">Content</a></li>
                    <li class="nav-item"><a href="<%= import_export_brand_locations_path %>">Import/Export</a></li>          
                    <% if current_page?(brand_locations_path(@brand.id)) || current_page?(brand_images_path(@brand.id)) || current_page?(brand_contents_path(@brand.id)) %>
                    <li><input class="form-control hidden-xs hidden-sm" placeholder="<%= @searchPlaceholder %>" ng-model="searchFilter"></li>
                    <% end %>


                    <li class="nav-item"><%= link_to "Sign Out", "/users/sign_out", method: :delete if user_signed_in? %></li>

                  </ul><!--//nav-->
              </div><!--//navabr-collapse-->
          </nav><!--//main-nav-->           
      </div><!--//container-->

      <div class="filter-cms-bar ">
        <div class="container">
            <div class="row">
              <div class="col-md-12">

                <div class="btn-group">
                  <% if current_page?(brand_locations_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('business_name')">
                      Filter by Name <span class="caret"></span>
                    </button>

                  <% elsif current_page?(brand_images_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('image_name')">
                      Filter by Name <span class="caret"></span>
                    </button>
                  <% elsif current_page?(brand_contents_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('content_name')">
                      Filter by Name <span class="caret"></span>
                    </button>
                  <% end %>
                </div>

                <div class="btn-group">
                  <% if current_page?(brand_locations_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('updated_at')">
                      Filter by Updated At <span class="caret"></span>
                    </button>

                  <% elsif current_page?(brand_images_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('updated_at')">
                      Filter by Updated At <span class="caret"></span>
                    </button>
                  <% elsif current_page?(brand_contents_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('updated_at')">
                      Filter by Updated At <span class="caret"></span>
                    </button>
                  <% end %>
                </div>

                <div class="btn-group">
                  <% if current_page?(brand_locations_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('created_at')">
                      Filter by Created At <span class="caret"></span>
                    </button>

                  <% elsif current_page?(brand_images_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('created_at')">
                      Filter by Created At <span class="caret"></span>
                    </button>
                  <% elsif current_page?(brand_contents_path(@brand.id)) %>
                    <button class="btn btn-cta-cms btn-xs dropdown-toggle hidden-xs" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ng-click="sortBy('created_at')">
                      Filter by Created At <span class="caret"></span>
                    </button>
                  <% end %>
                </div>
                
                <% if current_page?(brand_locations_path(@brand.id)) %> 
                  <%= link_to "Add new location", new_brand_location_path, class: "btn btn-cta-cms btn-xs pull-right" %>

                  <br>
                  <br>
                  <input class="form-control visible-xs visible-sm" placeholder="<%= @searchPlaceholder %>" ng-model="searchFilter">
                <% elsif current_page?(brand_images_path(@brand.id)) %>
                  <%= link_to "Add new image", new_brand_image_path(@brand), class: "btn btn-cta-cms btn-xs pull-right" %>

                  <br>
                  <br>
                  <input class="form-control visible-xs visible-sm" placeholder="<%= @searchPlaceholder %>" ng-model="searchFilter">
                <% elsif current_page?(brand_contents_path(@brand.id)) %>
                  <%= link_to "Add new content", new_brand_content_path(@brand), class: "btn btn-cta-cms btn-xs pull-right" %>

                  <br>
                  <br>
                  <input class="form-control visible-xs visible-sm" placeholder="<%= @searchPlaceholder %>" ng-model="searchFilter">
                <% end %>
            </div>
          </div>
        </div>
      </div>

  </header><!--//header-->

  <div class="container">
    <% flash.each do |name, message| %>
      <div class="alert alert-<%= name %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
  </div>

  <%= yield %>

  <!-- ******FOOTER****** --> 
  <div class="bottom-cms-bar">
      <div class="container">
          <div class="row">
              <small class="copyright col-md-6 col-sm-6 col-xs-12">Copyright @ <%= Time.now.year %> <a href="#"><%= site_name %></a></small>

          </div><!--//row-->
      </div><!--//container-->
  </div><!--//bottom-bar-->

  </div><!-- NG-CONTROLLER END -->
  </div><!-- NG-APP END -->

</body>
</html>

app/views/layouts/directory.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if !@brand.images.where(image_category: 'favicon').first.blank? %>
    <link rel="icon" type="image/png" href="<%= @brand.images.where(image_category: 'favicon').first.image.url %>">
  <% end %>

  <title><%= @brand.brand_meta_title %></title>
  <meta name="description" content="<%= @brand.brand_meta_description %>">
  <meta name="keywords" content="<%= @brand.brand_meta_keywords %>">
  <meta name="viewport" content="width=device-width">

  <%= stylesheet_link_tag    'location_application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<% if !@brand.primary_color.blank? && !@brand.secondary_color.blank? && !@brand.tertiary_color.blank? %>
  <style>
    a {
      color: <%= @brand.secondary_color %>;
    }
    a:hover {
      color: <%= @brand.primary_color %>;
    }
    .header h1.logo a {
      color: <%= @brand.primary_color %>;
    }
    .header h1.logo a:hover {
      color: <%= @brand.secondary_color %>;
    }
    .header .main-nav .navbar-toggle {
        background: <%= @brand.secondary_color %>;
    }
    .header .main-nav .navbar-toggle:hover {
        background: <%= @brand.secondary_color %>;
    }
    .header .main-nav .nav .nav-item a:hover {
      color: <%= @brand.primary_color %>;
    }

    .header .main-nav .nav .nav-item.active {
      color: <%= @brand.primary_color %>;
    }
    .promo .social {
      background: <%= @brand.primary_color %>;
    }
  </style>
<% end %>

<body id="location-page">

  <section class="section">
  <!-- ******HEADER****** --> 
  <header id="header" class="header">  
      <div class="container">            
          <h1 class="logo pull-left">
              <a href="#promo">
                <% if @brand.images.where(image_category: 'logo').take %>  
                  <span class="logo-title brand-logo"><img src="<%= @brand.images.where(image_category: 'logo').first.image.logo %>"></span>
                <% else %>
                  <span class="logo-title"><%= @brand.brand_name %></span>
                <% end %>
              </a>
          </h1><!--//logo-->              
          <nav id="main-nav" class="main-nav navbar-right" role="navigation">
              <div class="navbar-header">
                  <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button><!--//nav-toggle-->
              </div><!--//navbar-header-->            
              <div class="navbar-collapse collapse" id="navbar-collapse">
                  <ul class="nav navbar-nav">
                  </ul><!--//nav-->
              </div><!--//navabr-collapse-->
          </nav><!--//main-nav-->           
      </div><!--//container-->
  </header><!--//header-->

  
  <div class="container">
    <% flash.each do |name, message| %>
        <div class="alert alert-<%= name %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message %>
        </div>
      <% end %>
  </div>

  <% if !@brand.images.where(image_category: 'header').first.blank? %>
    <!-- ******PROMO****** --> 
    <section id="promo" class="promo section">  
        <div class="container intro">
          <% if !@brand.brand_tagline_title.blank? %>
            <h2 class="title"><%= raw @brand.brand_tagline_title %></h2>
            <p class="summary"><%= raw @brand.brand_tagline_summary %></p>
          <% end %>

        </div><!--//intro-->
        
        <div class="fixed-container">
            
            <div class="social text-center">
                <div class="container">
                    <span class="line"></span>    
                </div>         
            </div><!--//social-->   
        </div>  
        <div class="bg-slider-wrapper">
            <div id="bg-slider" class="flexslider bg-slider">
                <ul class="slides">
                    <li class="slide slide-header"><img class="image-respond" src="<%= @brand.images.where(image_category: 'header').first.image.header %>"></li>
                    <!-- <li class="slide slide-1"></li> -->
                    <!-- <li class="slide slide-2"></li> -->
                    <!-- <li class="slide slide-3"></li> -->
                </ul>
            </div>
        </div><!--//bg-slider-wrapper--> 
    </section>
    <!--//promo-->
  <% end %>

  <section class="content">
    <div class="container">
      <h1><%= @brand.brand_name %> Locations</h1>
      
      <% @locations.each do |state| %>
        <h2><%= state[0] %></h2>
        
        <% state[1].each do |city| %>
        <div class="row">
          <div class="container">
            <div class="col-md-12">
              <h4><%= city[0] %></h4>
            </div>

            <% city[1].each do |location| %>
            <div class="row">
              <div class="container">
                <div class="col-md-12">
                  <div class="col-md-12">
                    <% if location.slug %>
                      <p><a href="/<%= location.slug %>"><%= location.business_name %></a></p>
                    <% else %>
                      <p><a href="/<%= location.id %>"><%= location.business_name %></a></p>
                    <% end %>
                  </div>
                </div><!-- /.col-lg-4 -->
              </div>
            </div>
            <% end %>
          <% end %>
          </div>
        </div><!-- /.row -->
        
      <% end %>
        
    </div>
  </section>
  </section>

  <div class="container">
    <!-- FOOTER -->
    <footer>
      <!-- <p class="pull-right"><a href="#">Back to top</a></p> -->
      <p>&copy; <%= Time.now.year %> <%= @brand.brand_name %> <!-- &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a> --></p>
    </footer>
  </div><!-- /.container -->

  </body>
</html>